image: docker:stable
services:
  - name: docker:dind
    alias: thedockerhost

  
stages:
  - build

variables:
  IMAGE: registry.gitlab.com/medilane-group/medilane-api
  # Tell docker CLI how to talk to Docker daemon; see
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-docker-in-docker-executor
  DOCKER_HOST: tcp://thedockerhost:2375/
  # Use the overlayfs driver for improved performance:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  tags: 
    - medilane
  script:
    - apk add --no-cache bash python3
    - ls -la
    - docker build -t $IMAGE -f deploy/Dockerfile .
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PWD registry.gitlab.com
    - docker push $IMAGE
  only:
      - develop
