image: docker:latest
services:
  - name: docker:18.09-dind
    alias: docker
    command: [ "--tls=false" ]

  
stages:
  - build

variables:
  IMAGE: registry.gitlab.com/medilane-group/medilane-api

build:
  stage: build
  tags: 
    - medilane
  script:
    - ls -la
    - docker build -t $IMAGE -f deploy/Dockerfile .
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PWD registry.gitlab.com
    - docker push $IMAGE
  only:
      - develop
